
///////
// Network + Layer Configuration.
// File automatically generated by convert_caffemodel.py
// from deploy.prototxt and random/weight_iter_300.caffemodel
// (c) 2016 David Gschwend
///////

#ifndef _NETWORK_H_
#define _NETWORK_H_

// Size Limits for this Network
const int MAX_NUM_LAYERS = 14;
const int MAX_WEIGHTS_PER_LAYER = 147584;
const int MAX_IMAGE_CACHE_SIZE = 16384;
const int MAX_INPUT_PER_LAYER = 262144;
const int MAX_NUM_CHOUT = 128;
const int MAX_DIMENSION = 64;
const int MAX_CHANNELS = 128;

const int TOTAL_NUM_WEIGHTS = 502304;
const int TOTAL_NUM_INPUTS = 540640;
const int TOTAL_NUM_OUTPUTS = 528928;
const int TOTAL_DRAM_IO = 1571872;

const int DRAM_DEPTH = 0;
const float TEST_RESULT_EXPECTED = 0.00;

// Mean Pixel for ImageNet Data
const float MEAN_R = 104;
const float MEAN_G = 117;
const float MEAN_B = 123;

// include after definitions to allow bit-width calculations
#include "netconfig.hpp"

network_t *get_network_config();

#endif
