
///////
// Network + Layer Configuration.
// File automatically generated by convert_caffemodel.py
// from deploy.prototxt and random/weight_iter_300.caffemodel
// (c) 2016 David Gschwend
///////

#include "network.hpp"
network_t *get_network_config() {
  network_t *net = new network_t(14, 502304);

  // Layer Attributes: ( NAME   ,   W,   H,   CI,  CO, K, P, S, R, S1, S2, GP)
  addLayer(net, layer_t("c0    ",  64,  64,    3,  64, 3, 1, 1, 0,  0,  0,  0));
  addLayer(net, layer_t("cpool1",  64,  64,   64,  64, 3, 0, 2, 0,  0,  0,  0));
  addLayer(net, layer_t("c2    ",  31,  31,   64, 128, 3, 1, 1, 0,  0,  0,  0));
  addLayer(net, layer_t("cpool3",  31,  31,  128, 128, 3, 0, 2, 0,  0,  0,  0));
  addLayer(net, layer_t("c4    ",  15,  15,  128,  64, 3, 1, 1, 0,  0,  0,  0));
  addLayer(net, layer_t("c5    ",  15,  15,   64,  64, 3, 1, 1, 0,  0,  0,  0));
  addLayer(net, layer_t("c6    ",  15,  15,   64,  64, 3, 1, 1, 0,  0,  0,  0));
  addLayer(net, layer_t("cpool7",  15,  15,   64,  64, 3, 0, 2, 0,  0,  0,  0));
  addLayer(net, layer_t("c8    ",   7,   7,   64,  32, 3, 1, 1, 0,  0,  0,  0));
  addLayer(net, layer_t("c9    ",   7,   7,   32,  32, 3, 1, 1, 0,  0,  0,  0));
  addLayer(net, layer_t("c10   ",   7,   7,   32,  32, 3, 1, 1, 0,  0,  0,  0));
  addLayer(net, layer_t("c11   ",   7,   7,   32,  32, 3, 1, 1, 0,  0,  0,  0));
  addLayer(net, layer_t("cpool12",   7,   7,   32,  32, 3, 0, 2, 0,  0,  0,  0));
  addLayer(net, layer_t("cfc13 ",   3,   3,   32,  64, 1, 0, 1, 0,  0,  0,  1));

  net->num_weights = 502304;
  const char* filename = "weights.bin";
  loadWeightsFromFile(net, filename);
  return net;
}
